services:
  ollama:
    build:
      context: ./ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app-network
    environment:
      - OLLAMA_MODEL=qwen2.5:0.5b

  langchain:
    build:
      context: ./langchain
    volumes:
      - ./langchain:/app
    networks:
      - app-network
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=qwen2.5:0.5b
    command: poetry run python serve.py

networks:
  app-network:


volumes:
  ollama:
